<?php

namespace app\admin\controller;

use app\common\controller\Admin;
use app\common\model\Setting as SettingModel;

class Setting extends Admin
{

    public function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub

        if($this->request->isPost()){
            $type = $this->request->action();
            $post = input('post.');


            var_dump($post);
            exit;
        }
    }


    public function basic(){
        return $this->fetch();
    }



}