<?php

namespace app\common\controller;

use app\common\model\Groups;
use app\common\model\Policys;
use app\common\model\Users;
use think\Controller;

class Home extends Controller
{

    protected $middleware = ['UserLoginCheck'];

    protected $userInfo = [];

    protected $groupData = [];

    public function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->userInfo = (new Users())->login_info('default');

        $this->groupData = Groups::where('id',$this->userInfo['group'])->find();

    }

    protected function getPolicy(): array
    {
        $policy = Policys::where('id',$this->groupData['policy_id'])->find()->toArray();

        $policy['config'] = json_decode($policy['config'],true);

        return $policy;
    }


}